### ISSUE TITLE
API consistency: `duration`, `interval` and other time-related parameters

### ISSUE THREAD

**Issue by lkorczowski** [lkorczowski/Tinnitus-n-Sleep#25]
As this discussion rises, we should handle this issue before it becomes too big:
- what is the rule for time-related parameters ?

Here are some thoughts:
- time-based parameters are better handled in samples as the behaviour is less prone to machine error (e.g. weird behaviour of `round()`-like functions).
- if in samples, we let the user double-check the parameters, it is extra work
- if in seconds, it is consistent with ``mne`` but it requires an additional `sfreq` parameter (or is it?)

Proposed solution:
- as most of the matlab signal processing functions work, I advice to have for all functions the `sfreq=1` parameters. Therefore without explicit call of the parameters, all time-related parameters are set to an "equivalent` in samples.

Here is some caveats:
- converting and roundings will be handled by ALL functions when necessary. Therefore, we should build a very consistent way to handle time-based parameters, i.e. having functions to `convert_time_to_samples`, `check_if_samples_array`, etc.
- naming convention should be as consistent and as user-friendly as possible. Therefore universal names such as `duration` or `interval` should always be used if the function can handle both samples or time. If not, the function parameters should be explicit e.g. `samples_duration`, `time_duration` and these should be used with scarcity (only in low-level or private functions).

**Comment by RobinGuillard** [comment]
From I have experienced on the past week, I would advize to go for interval and duration in seconds. Why? Because for the study of bruxism events, scoring methods are based on durations in seconds (for example, the rules are: bursts should last "at least 0,25s", burst should be apart of less than 3s to be reunited within the same episode, and tonic episodes are at least 2s long). As well, using seconds instead of samples makes it easier for the generation of the clinical report.
All in all, as for many cases we are "undecided" for samples or seconds, but we are "imposed" for these cases, it would appear more logical to use time in seconds.
But I agree, it imposes consistency regarding hte rounding operations to pass from time to samples.

**Comment by lkorczowski** [comment]
We had a huge rounding issue while using time. Therefore, now the routine on all epoching strategy is in samples to avoid shift between epochs, see #78
