### ISSUE TITLE
Dealing with merge valid labels interpolation issue

### ISSUE THREAD

**Issue by RobinGuillard** [lkorczowski/Tinnitus-n-Sleep#78]
As formerly described, we have an issue on the interpolation process from large to smaller epochs. Why? there is often a "rounding effect" on the number of epochs between larger and smaller epochs (fexample: for 10,75s of recording, we have 10 epochs of 1s and 43 epochs of 250ms).
Solution proposed : we crop the end of ALL our recordings so to have a duration which is a multiple of 0.992s (248 samples).
It's brutal, but it works.
What do you think?

**Comment by RobinGuillard** [comment]
We'll keep as an enhancement option the possibility to secure the merge_label_list function, notably dealing with the case where there is at least 3 different lengths of inputs...

**Comment by lkorczowski** [comment]
I'm looking into it this evening.

**Comment by lkorczowski** [comment]
OK. So my conclusion right now is
1. proportional duration and interval should be used as it is the easier to deal with this issue
2. interpolation is a bad idea because it can go horribly wrong without as knowing (i.e. if the user one interval of labels is 62 samples and the other is non-proportional such as 250 samples). Interpolating will work all the time but the labels can be shifted non uniformly across all signal if not proportional.

for now, I'll advice to use a simple warning and this is user's job to provide proportional number of epochs.
